#!/bin/bash

if [ -z "$GIT_DIRS" ]; then
    echo "GIT_DIRS is not set"
    echo "export GIT_DIRS=/space/delimited /list/of/dirs"
    exit 1
fi


## Test function
function findIn() {
    for i in $(find "$1" -type d -name *.git); do
        c=`git -C $(dirname $i) status --porcelain | wc -l`
        if [ $c -gt 0 ]; then
            echo $(dirname $i)
        fi
    done
}


## Loop through paths
for dir in $GIT_DIRS; do
    if [ -d "$dir" ]; then
        findIn $dir
    fi
done

