#!/usr/bin/python

import boto3
from os import listdir, environ 
from os.path import isdir, abspath

try:
    localPath = environ['GIT_DIR']
except KeyError:
    raise SystemExit("GIT_DIR env var is not set")

repoNames = []

for repo in repoList["repositories"]:
    repoNames.append(repo["repositoryName"])

#print(repoNames)

for dirname in localPath:
    if isdir(dirname):
        for entity in listdir(dirname):
            path = abspath("{}/{}".format(dirname, entity))
            if isdir(path):
                if entity not in repoNames:
                    print(path)

