#!/bin/bash
IFS=:

## A list of paths to test
## ":" delimited
PATHS=/home/e1ts7sx/gits:/home/rsigler/gits

## Test function
function findIn() {
    for i in $1/* ; do 
        if [ -d "$i/.git" ]; then
            git -C $i remote update > /dev/null
            c=`git -C $i status -uno --porcelain | wc -l`
            if [ $c -gt 0 ]; then
                echo "$i"
            fi
        fi
    done
}

## Loop through paths
for dir in $PATHS; do
    if [ -d "$dir" ]; then
        findIn $dir
    fi
done




