#!/usr/bin/python

import boto3
import pprint

session = boto3.session.Session(profile_name="code-commit")
client = session.client('codecommit')
repoList = client.list_repositories()

pp = pprint.PrettyPrinter(indent=4)

for repo in repoList["repositories"]:
    repoName = repo["repositoryName"]
    repoData = client.get_repository(repositoryName = repoName)
    sshURL = repoData["repositoryMetadata"]["cloneUrlSsh"]
    #print(repoName, sshURL)
    print("git clone {}".format(sshURL))

