#!/bin/bash

## run on a dir of bare repos
## git clone --base ${url}

for i in *.git; do
    if [ -d $i ]; then
        repo=${i%.git}
        aws --profile code-commit codecommit create-repository --repository-name $repo
        if [ $? -ne 0 ]; then
            exit
        fi
        git -C $i push --mirror ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/$repo
        if [ $? -ne 0 ]; then
            exit
        fi
        mv $i done/
    fi
done
