#!/usr/bin/env python3

import boto3
import argparse

def run():
    # Set up the arg parser. Require repo name  and description
    parser = argparse.ArgumentParser(description='Delete AWS Code Commit repo')
    parser.add_argument("--repo", "-r", required=True, type=str, help="Repo name")
    parser.add_argument("--confirm", "-c", required=True, action="store_true", help="Confirm repo deletion")
    args = parser.parse_args()

    # set up the AWS session
    session = boto3.session.Session()
    client = session.client('codecommit')

    # Delete the repo
    client.delete_repository(repositoryName=args.repo)
    print("{} deleted".format(args.repo))

if __name__ == "__main__":
    run()
