#!/usr/bin/env python3

import boto3
import argparse

def run():
    # Set up the arg parser. Require repo name  and description
    parser = argparse.ArgumentParser(description='Create AWS Code Commit repo')
    parser.add_argument("--repo", "-r", required=True, type=str, help="Repo name")
    parser.add_argument("--descr", "-d", required=True, type=str, help="Repo description")
    args = parser.parse_args()

    # set up the AWS session
    session = boto3.session.Session()
    client = session.client('codecommit')

    # Create the repo
    repo = client.create_repository(repositoryName=args.repo, repositoryDescription=args.descr)
    # Get the metadata for the new repo
    repoData = repo["repositoryMetadata"]
    # Print out some useful stuff
    print("Name:   ", repoData["repositoryName"])
    print("Descr:  ", repoData["repositoryDescription"])
    print("SSH Url:", repoData["cloneUrlSsh"])

if __name__ == "__main__":
    run()
