#!/usr/bin/env python3

import boto3
import argparse

def run():
    # Set up the arg parser. Require repo name  and description
    parser = argparse.ArgumentParser(description='Set/Update AWS Code Commit repo description')
    parser.add_argument("--repo", "-r", required=True, type=str, help="Repo name")
    parser.add_argument("--descr", "-d", required=True, type=str, help="Description")
    args = parser.parse_args()

    # set up the AWS session
    session = boto3.session.Session()
    client = session.client('codecommit')

    # Delete the repo
    client.update_repository_description(repositoryName=args.repo, repositoryDescription=args.descr)

if __name__ == "__main__":
    run()
