#!/usr/bin/env python3

import boto3
import argparse

def run():
    # Set up the arg parser. Require repo name  and description
    parser = argparse.ArgumentParser(description='Set/Update AWS Code Commit repo description')
    parser.add_argument("--source", "-s", required=True, type=str, help="Repo name")
    parser.add_argument("--target", "-t", required=True, type=str, help="New repo name")
    args = parser.parse_args()

    # set up the AWS session
    session = boto3.session.Session()
    client = session.client('codecommit')

    # Delete the repo
    client.update_repository_name(oldName=args.source, newName=args.target)

if __name__ == "__main__":
    run()
