#!/usr/bin/env python3

from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication
import argparse
import os

try:
    TFS_TOKEN=os.environ["TFS_TOKEN"]
    TFS_ORG_URL=os.environ["TFS_ORG_URL"]
except KeyError as e:
   print(f"Env var not defined {e}")
   print("export TFS_TOKEN and TFS_ORG_URL")
   raise SystemExit
except:
    raise

parser = argparse.ArgumentParser(description="Get repo ssh url")
parser.add_argument("--repo_id", "-r", type=str, required=True, help="Project ID")
args = parser.parse_args()

# Create a connection to the org
credentials = BasicAuthentication('', TFS_TOKEN)
connection = Connection(base_url=TFS_ORG_URL, creds=credentials)

# Get a client (the "core" client provides access to projects, teams, etc)
git_client = connection.clients.get_git_client()

for repo in git_client.get_repositories(project=args.repo_id):
	print(f"git clone ssh://{repo.ssh_url}")
